name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cargo build -p logger
        cargo build -p decrypt_log
        cargo build -p mmap_demo
        bash check_unsafe.sh
        cargo fmt --check
        
    - name: Run tests
      run: | 
        cargo test -- --test-threads=1
